### ISSUE TITLE
Project High Level todo list

### ISSUE THREAD

**Issue by gurgalex** [gurgalex/api-save-limiter#1]
# Unlimited upload and rate limit
- [ ] implementation of save file
- any json string <= 1kb

- [ ] user auth service
- auth0- free for up to 7000 active users + no credit card required

## Security requirements
- nobody else should be able to access/modify another's save

Financial requirements
- [ ] save file size enforcement of no larger than 1kb
- [ ] rate limit save to 10 seconds and load of 20 seconds per user account
- [ ] all restrictions are in place server/API as well
- [ ] Set up alert for S3 not to exceed 1MB
 
draft technologies used
[ ] - rate limit server-side: AWS API Gateway HTTP throttle limits on each endpoint. $1/1M requests per 512KB https://aws.amazon.com/api-gateway/pricing/
    https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html#apig-request-throttling-account-level-limits
    API Gateway console by using the Default Method Throttling setting in Stages. 

[ ] - rate limit client-side: throttle npm library. https://www.npmjs.com/package/p-throttle
[ ]- size limit server-side: check size in AWS lambda fn
[ ] - size limit client-side: check inside upload fn

Objectives
1. Learn about AWS billing monitors/alerts/estimates
2. Learn about setting up AWS rate limit on endpoints
3. S3 storage using small save files, set up alert for storage
4. Learn about 0auth2 providers
